### ISSUE TITLE
cannot use System.Drawing.Color

### ISSUE THREAD

**Issue by macleod1982** [xiongfang/UnrealCS#11]
I am trying to use System.Drawing.Color structure, but getting an error.

I've already copied 

c:\Program Files\Mono\lib\mono\4.6.2-api\System.Drawing.dll 
to 
\Content\Scripts\framework\

.cs 
Color color = Color.Aqua;

It compiles, but throwing exception on run

LogMono:Warning: Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Game.RotateMe.BeginPlay () <0x1de015f2660 + 0x0004c> in <filename unknown>:0

**Comment by macleod1982** [comment]
I've used a wrong version of System.Drawing.dll. It works with the correct one.

**Comment by ghost** [comment]
Please close issue if your issue was fixed.
