### ISSUE TITLE
Using an external C# DLL

### ISSUE THREAD

**Issue by macleod1982** [xiongfang/UnrealCS#9]
I am trying to use a very simple c#.dll with the plugin. It has only one test function, but I always get an error message, in unreal engine when I call my test function.

LogMono:Warning: Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'DLLTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'DLLTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

Is it possible to use external DLLs with the plugin? If so, where should I place my dll ?

**Comment by Xerios** [comment]
I haven't tried UnrealCS yet but looking at your issue, I'd say try getting assembly path with one of the working demos maybe that might help you get the proper path.

**Comment by xiongfang** [comment]
Place in this directory : UnrealCS/Engine/Plugins/UnrealCS/Scripts/framework/
Then create a new project
